### ISSUE TITLE
how can this hostname be changed? its the same across all installs currently

### ISSUE THREAD

**Issue by sudogreg** [Freekers/automated-pihole#7]
all cached queries are pulling from -     unbound.automatedpihole_pihole_net

and would like to try and show the actual hostname of the server

**Comment by Freekers** [comment]
Try the following; edit the docker-compose.yml by hand and add `hostname: your_hostname` under the `unbound` services directive. I.e.:

```
  unbound:
   image: secns/unbound:latest
   restart: always
   container_name: unbound
   hostname: your_hostname
   environment:
    - DO_IPV6=no
    - HIDE_VERSION=yes
   volumes:
    - /opt/automated-pihole/unbound/pi-hole.conf:/etc/unbound/unbound.conf.d/pi-hole.conf
    - /opt/automated-pihole/unbound/root.hints:/var/lib/unbound/root.hints
   networks:
      pihole_net:
        ipv4_address: 10.0.0.2
```
